sketchbook_root = '.'
base_url = 'https://yacho-demo.netlify.app/'
author = 'eqs'
avatar = 'chi.png'
bio = """
Creative Coder
"""
custom_css = 'custom.css'

[social]
home = "https://www.eqseqs.work"
twitter = "eqs_work"
github = "eqs"
