sketchbook_root = '.'
base_url = 'https://yacho-demo.netlify.app/'
author = 'eqs'
avatar = 'chi.png'
bio = """
An example user
"""
custom_css = 'custom.css'

title = 'yacho-example'

[code]
line_number = false
copy_button = true

[social]
home = "https://github.com/eqs/yacho"
twitter = "eqs_work"
github = "eqs"
