name: CI

on:
    push:
        branches:
            - master

jobs:
    deploy:
        runs-on: ubuntu-18.04
        steps:
        - name: Python 3.9
          uses: actions/setup-python@v2
          with:
              python-version: '3.9'

        - name: Checkout
          uses: actions/checkout@v2

        - name: Clone eqs/yacho
          uses: actions/checkout@v2
          with:
              repository: eqs/yacho
              ref: master
              path: ~/yacho

        - name: Setup eqs/yacho
          working-directory: ~/yacho
          run: pip install -e .

        - name: Build web page
          run: yacho build

        - name: Push to gh-pages
          uses: peaceiris/actions-gh-pages@v3
          with:
              github_token: ${{ secrets.GITHUB_TOKEN }}
              publish_branch: gh-pages
              publish_dir: dist/
